### ISSUE TITLE
Create All Steps Definition only creates for one step in the feature file

### ISSUE THREAD

**Issue by panama69** [HPSoftware/octane-cucumber-jvm#3]
For a feature file containing:

Feature:Purchases
	Scenario: purchase shirts
		Given Jeff has bought a shirt for 50 dollars
		Then Jeff looks sharp

The expectation would be that the Given and the Then definitions would be created.  But only one is created and you would need to go back and create the other definition.

**Comment by sharonvardi** [comment]
@panama69 Thank you for using octane-cucumber-jvm.
The issues you are experiencing are **related to the IDE plugin for cucumber** you are using. You can open these issues for them.
octane-cucumber-jvm job is to create a custom report on runtime that can be later sent to ALM Octane for reporting gherkin test results.
