### ISSUE TITLE
In correct regex generation for lines with $

### ISSUE THREAD

**Issue by panama69** [HPSoftware/octane-cucumber-jvm#4]
If the following is in the feature file:
```
Given Jeff has bought a shirt for $50
```

and you create a step definition, you end up with
```
@Given("^Jeff has bought a shirt for \$(\\d+)$")
```
The issue is when you look at the feature file, it doesn't look covered and still shows as a step that needs a definition.

For the plugin to recognize the step, one must escape the escape as shown below
```
@Given("^Jeff has bought a shirt for \\$(\\d+)$")
```

**Comment by sharonvardi** [comment]
@panama69 Thank you for using octane-cucumber-jvm.
The issues you are experiencing are **related to the IDE plugin for cucumber** you are using. You can open these issues for them.
octane-cucumber-jvm job is to create a custom report on runtime that can be later sent to ALM Octane for reporting gherkin test results.
