### ISSUE TITLE
regexe recognition

### ISSUE THREAD

**Issue by panama69** [HPSoftware/octane-cucumber-jvm#5]
if I have a feature file such as:
```
Feature:Purchases
	Scenario: purchase shirts
		Given Jeff has bought a new shirt
		Then Jeff looks sharp
	Scenario: purchase old stuff
		Given Jeff has bought a old shirt
		Then Jeff looks sharp
	Scenario: purchase old stuff
		Given Jeff has bought a shirt
		Then Jeff looks sharp
```
Then having a step definitions file like
```
public class MyStepdefs {
    @Then("^Jeff looks sharp$")
    public void jeffLooksSharp() throws Throwable {
        // Write code here that turns the phrase above into concrete actions
        //throw new PendingException();
    }

    @Given("^Jeff has bought a (?:new )?|(?:old )?shirt$")
    public void jeffHasBoughtANewShirt() throws Throwable {
        // Write code here that turns the phrase above into concrete actions
        //throw new PendingException();
    }
}
```
should enable the plugin to recognize the that all 3 Given conditions are covered but it does not.

**Comment by sharonvardi** [comment]
@panama69 Thank you for using octane-cucumber-jvm.
This is a cucumber issue. You can open an issue for them.
But I can give you a tip here: For such cases you have the [Scenario Outline](https://github.com/cucumber/cucumber/wiki/Scenario-Outlines).

**Comment by panama69** [comment]
@sharonvardi I am confused how this is a cucumber issue?  When I run it, it runs just fine.  It is the plugin that doesn't seem to recognize that steps are covered based on the regex in the definition file.

And thank you for the tip on the Scenario Outline.  I am aware of this but the approach I was implementing above removes the need for the Scenario Outline and enables business users to use any form of the "Given" as the test is the same and not dependent on if one uses "new", "old" or no value for the shirt.

**Comment by sharonvardi** [comment]
@panama69 So I didn't understand your issue correctly. It's the IDE plugin issue then. 
octane-cucumber-jvm only participates on the run time. Any design time issue probably belongs to your IDE plugin.

**Comment by panama69** [comment]
@sharonvardi got it i miss understood what this was doing in the IDE.  Thanks.
